apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
        workaround: again-rolling
    spec:
      imagePullSecrets:
        - name: gitlab-auth # set by (kubectl create secret ... ) and used for pulling private image 
      containers:
        - image: registry.example.com/phpunch/chow-ni-car/frontend:__VERSION__
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 3000
          resources: {}
          env:
            - name: WORKAROUND
              value: rollingworkaround
            - name: API_ENDPOINT
              value: 35.234.58.120
      restartPolicy: Always
status: {}
